server:
  port: 2000
spring:
  application:
    name: service-course
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848	#注册中心地址
    sentinel:
      transport:
        dashboard: localhost:1111
  datasource:
    url: jdbc:mysql:///jsxm-course
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: mysql #jpa操作mysql
    show-sql: true  #把执行sql显示出来
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy #不用管
      ddl-auto: update #自动建表策略
    open-in-view: true #开启支持懒加载的filter,web环境才可用
    database-platform: org.hibernate.dialect.MySQL55Dialect #使用的mysql5.5方言
logging:
  level:
    cn.itsource: debug
feign:
  sentinel:
    enabled: true #熔断