server:
  port: 1000
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848	#注册中心地址
    gateway:
      discovery:
        locator:
          enabled: false #开放服务名访问方式
          lower-case-service-id: true #服务名小写
      routes:
        - id : service-user #指定服务名
          uri: lb://service-user #去注册中心找这个服务名
          predicates:    #断言，匹配访问的路径
            - Path=/user/**	#服务访问路径
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1	#请求转发的时候会去掉 /user访问路径
        - id: service-course #指定服务名
          uri: lb://service-course #去注册中心找这个服务名
          predicates:    #断言，匹配访问的路径
            - Path=/course/**    #服务访问路径
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1    #请求转发的时候会去掉 /user访问路径
        - id: service-shop #指定服务名
          uri: lb://service-shop #去注册中心找这个服务名
          predicates:    #断言，匹配访问的路径
            - Path=/shop/**    #服务访问路径
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1    #请求转发的时候会去掉 /user访问路径
        - id: service-order #指定服务名
          uri: lb://service-order #去注册中心找这个服务名
          predicates:    #断言，匹配访问的路径
            - Path=/order/**    #服务访问路径
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1    #请求转发的时候会去掉 /user访问路径
        - id: service-pay #指定服务名
          uri: lb://service-pay #去注册中心找这个服务名
          predicates:    #断言，匹配访问的路径
            - Path=/pay/**    #服务访问路径
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1    #请求转发的时候会去掉 /user访问路径

        - id: service-course #指定服务名
          uri: lb://service-course #去注册中心找这个服务名
          predicates: #断言，匹配访问的路径
            - Path=/course/**    #服务访问路径
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1    #请求转发的时候会去掉 /user访问路径

        - id: service-file #指定服务名
          uri: lb://service-file #去注册中心找这个服务名
          predicates: #断言，匹配访问的路径
            - Path=/file/**    #服务访问路径
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1    #请求转发的时候会去掉 /user访问路径
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allow-credentials: true
            allowed-headers: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
              - HEAD
              - CONNECT
              - TRACE
