server:
  port: 2010
spring:
  application:
    name: service-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848	#注册中心地址
    sentinel:
      transport:
        dashboard: localhost:1111
  datasource:
    url: jdbc:mysql:///jsxm-course
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300 #9200是图形界面端,9300代码端
logging:
  level:
    cn.itsource: debug